# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
robot_radius: 0.3  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  # if the robot is not circular

map_type: grid  #voxel

obstacle_layer:
  enabled:              true
  max_obstacle_height:  3.0
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             4
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 10.0
  raytrace_range: 15.0
  publish_voxel_map: false
  observation_sources:  scan  #scan  

  scan:
    data_type: LaserScan
    sensor_frame: base_laser
    topic: scan
    marking: true
    clearing: true
    min_obstacle_height: -5
    max_obstacle_height: 5
    # obstacle_range: 30
    # raytrace_range: 35

static_layer:
  enabled:              true

  

