global_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   update_frequency: 0.1
   publish_frequency: 0.1
   static_map: true
   transform_tolerance: 0.5
   inflation_layer_global:
     enabled:              true
     cost_scaling_factor:  5  # exponential rate at which the obstacle cost drops off (default: 10)
     inflation_radius:     5  # max. distance from an obstacle at which costs re incurred for planning paths.
   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: inflation_layer_global,         type: "costmap_2d::InflationLayer"}


 
